### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by Miccio-AN** [linuxmint/sticky#129] opened 2024-07-25 07:31 UTC
First of all thank you for your great software!
I use it with the Debian distribution and I would like to point out that with X11 everything works perfectly. Unfortunately, however, there are problems with Wayland. I would like to know if there is any possibility that support for Wayland on Debian will be improved in future releases. 
A thousand thanks!

**Comment by leigh123linux** [comment] 2024-07-25 07:38
Duplicate of https://github.com/linuxmint/wayland/issues/101

Wayland support will probably be added in the next couple of years, it's still low priority.

**Closed by leigh123linux** 2024-07-25 07:38 UTC
